package ub.info.prog2.HuayllasMiguel.vista;

import java.awt.CardLayout;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import ub.info.prog2.HuayllasMiguel.controlador.Controlador;

import ub.info.prog2.utils.ReproException;

/**
 *
 * @author MiguelDesktop
 */
public class AplicacionUB4 extends javax.swing.JFrame {

    Controlador control = new Controlador();

    CardLayout card;

    /**
     * Creates new form AplicacionUB4
     */
    public AplicacionUB4() {

        initComponents();
        card = (CardLayout) (panelCardLayout.getLayout());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addFileDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        examAddFileBtn1 = new javax.swing.JButton();
        fileTxtFile = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        caratulaTxtFile = new javax.swing.JTextField();
        autorTxtFile = new javax.swing.JTextField();
        examAddFileBtn2 = new javax.swing.JButton();
        tipoFileComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        onAddFileDialogBtn = new javax.swing.JButton();
        offAddFileDialogBtn = new javax.swing.JButton();
        saveDatesDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameSaveDatesTxtField = new javax.swing.JTextField();
        fileSaveDatesTxtField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        offSaveDatesBtn = new javax.swing.JButton();
        onSaveDatesBtn = new javax.swing.JButton();
        loadDatesDialog = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fileLoadDatesTxtField = new javax.swing.JTextField();
        onLoadDatesBtn = new javax.swing.JButton();
        offLoadDatesBtn = new javax.swing.JButton();
        addPortafolioDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameAddPortTxtField = new javax.swing.JTextField();
        sizeAddPortTxtField = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        addFilePortafolioDialog = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        repoList2 = new javax.swing.JList<>();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        stopBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        ciclicoBtn = new javax.swing.JToggleButton();
        randomBtn = new javax.swing.JToggleButton();
        playPBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        repoBtn = new javax.swing.JButton();
        portafoliosBtn = new javax.swing.JButton();
        labelImageReproductor = new javax.swing.JLabel();
        panelCardLayout = new javax.swing.JPanel();
        Repository = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        repoList = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Portafolios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        portafoliosList = new javax.swing.JList<>();
        addPortafolio = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        examAddFileBtn1.setText("Examinar...");
        examAddFileBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examAddFileBtn1ActionPerformed(evt);
            }
        });

        fileTxtFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileTxtFileActionPerformed(evt);
            }
        });

        jLabel1.setText("Archivo");

        jLabel2.setText("Caratula");

        jLabel3.setText("Autor");

        caratulaTxtFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caratulaTxtFileActionPerformed(evt);
            }
        });

        examAddFileBtn2.setText("Examinar...");
        examAddFileBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examAddFileBtn2ActionPerformed(evt);
            }
        });

        tipoFileComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Musica", "Imagen" }));
        tipoFileComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoFileComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo");

        onAddFileDialogBtn.setText("Aceptar");
        onAddFileDialogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddFileDialogBtnActionPerformed(evt);
            }
        });

        offAddFileDialogBtn.setText("Cancelar");
        offAddFileDialogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offAddFileDialogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(fileTxtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(examAddFileBtn1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caratulaTxtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(tipoFileComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(autorTxtFile))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(examAddFileBtn2)))
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(offAddFileDialogBtn)
                .addGap(65, 65, 65)
                .addComponent(onAddFileDialogBtn)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examAddFileBtn1)
                    .addComponent(fileTxtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(caratulaTxtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(examAddFileBtn2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autorTxtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoFileComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onAddFileDialogBtn)
                    .addComponent(offAddFileDialogBtn))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout addFileDialogLayout = new javax.swing.GroupLayout(addFileDialog.getContentPane());
        addFileDialog.getContentPane().setLayout(addFileDialogLayout);
        addFileDialogLayout.setHorizontalGroup(
            addFileDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFileDialogLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        addFileDialogLayout.setVerticalGroup(
            addFileDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        String fichero;

        jLabel5.setText("Nombre");

        jLabel6.setText("Archivo");

        jButton1.setText("Examinar..");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        offSaveDatesBtn.setText("Cancelar");
        offSaveDatesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offSaveDatesBtnActionPerformed(evt);
            }
        });

        onSaveDatesBtn.setText("Aceptar");
        onSaveDatesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSaveDatesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameSaveDatesTxtField))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fileSaveDatesTxtField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 210, Short.MAX_VALUE)
                        .addComponent(offSaveDatesBtn)
                        .addGap(18, 18, 18)
                        .addComponent(onSaveDatesBtn)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nameSaveDatesTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fileSaveDatesTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onSaveDatesBtn)
                    .addComponent(offSaveDatesBtn))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout saveDatesDialogLayout = new javax.swing.GroupLayout(saveDatesDialog.getContentPane());
        saveDatesDialog.getContentPane().setLayout(saveDatesDialogLayout);
        saveDatesDialogLayout.setHorizontalGroup(
            saveDatesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saveDatesDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        saveDatesDialogLayout.setVerticalGroup(
            saveDatesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton2.setText("Examinar..");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Archivo");

        onLoadDatesBtn.setText("Aceptar");
        onLoadDatesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLoadDatesBtnActionPerformed(evt);
            }
        });

        offLoadDatesBtn.setText("Cancelar");
        offLoadDatesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offLoadDatesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loadDatesDialogLayout = new javax.swing.GroupLayout(loadDatesDialog.getContentPane());
        loadDatesDialog.getContentPane().setLayout(loadDatesDialogLayout);
        loadDatesDialogLayout.setHorizontalGroup(
            loadDatesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadDatesDialogLayout.createSequentialGroup()
                .addGroup(loadDatesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loadDatesDialogLayout.createSequentialGroup()
                        .addContainerGap(216, Short.MAX_VALUE)
                        .addComponent(offLoadDatesBtn)
                        .addGap(18, 18, 18)
                        .addComponent(onLoadDatesBtn))
                    .addGroup(loadDatesDialogLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileLoadDatesTxtField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGap(20, 20, 20))
        );
        loadDatesDialogLayout.setVerticalGroup(
            loadDatesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadDatesDialogLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(loadDatesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel7)
                    .addComponent(fileLoadDatesTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(loadDatesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onLoadDatesBtn)
                    .addComponent(offLoadDatesBtn))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel8.setText("Nombre");

        jLabel9.setText("Tamaño");

        sizeAddPortTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeAddPortTxtFieldActionPerformed(evt);
            }
        });

        jButton9.setText("Aceptar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Cancelar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(sizeAddPortTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nameAddPortTxtField))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nameAddPortTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sizeAddPortTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addPortafolioDialogLayout = new javax.swing.GroupLayout(addPortafolioDialog.getContentPane());
        addPortafolioDialog.getContentPane().setLayout(addPortafolioDialogLayout);
        addPortafolioDialogLayout.setHorizontalGroup(
            addPortafolioDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        addPortafolioDialogLayout.setVerticalGroup(
            addPortafolioDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPortafolioDialogLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        repoList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(repoList2);

        jButton12.setText("Agregar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Cancelar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addGap(30, 30, 30)
                        .addComponent(jButton12))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addGap(0, 65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addFilePortafolioDialogLayout = new javax.swing.GroupLayout(addFilePortafolioDialog.getContentPane());
        addFilePortafolioDialog.getContentPane().setLayout(addFilePortafolioDialogLayout);
        addFilePortafolioDialogLayout.setHorizontalGroup(
            addFilePortafolioDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addFilePortafolioDialogLayout.setVerticalGroup(
            addFilePortafolioDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        jPanel1.setBackground(new java.awt.Color(27, 27, 47));

        jPanel2.setBackground(new java.awt.Color(31, 64, 104));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        stopBtn.setBackground(java.awt.Color.white);
        stopBtn.setText("Stop");
        stopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnActionPerformed(evt);
            }
        });

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        ciclicoBtn.setText("Ciclico");
        ciclicoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciclicoBtnActionPerformed(evt);
            }
        });

        randomBtn.setText("Random");
        randomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomBtnActionPerformed(evt);
            }
        });

        playPBtn.setText("Play");
        playPBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        playPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playPBtnActionPerformed(evt);
            }
        });

        jButton3.setText("Pause");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ciclicoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(randomBtn))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopBtn)
                    .addComponent(nextBtn)
                    .addComponent(ciclicoBtn)
                    .addComponent(randomBtn)
                    .addComponent(playPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        repoBtn.setText("Repositorios");
        repoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repoBtnActionPerformed(evt);
            }
        });

        portafoliosBtn.setText("Portafolios");
        portafoliosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portafoliosBtnActionPerformed(evt);
            }
        });

        labelImageReproductor.setIcon(new javax.swing.ImageIcon("C:\\Users\\MiguelDesktop\\Documents\\reproductorDeMusicaUB\\iconMusic.jpg")); // NOI18N

        panelCardLayout.setLayout(new java.awt.CardLayout());

        Repository.setBackground(new java.awt.Color(228, 63, 90));
        Repository.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jScrollPane2.setViewportView(repoList);

        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Borrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RepositoryLayout = new javax.swing.GroupLayout(Repository);
        Repository.setLayout(RepositoryLayout);
        RepositoryLayout.setHorizontalGroup(
            RepositoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RepositoryLayout.createSequentialGroup()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jButton6))
            .addGroup(RepositoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        RepositoryLayout.setVerticalGroup(
            RepositoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RepositoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(RepositoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)))
        );

        panelCardLayout.add(Repository, "card2");

        Portafolios.setBackground(new java.awt.Color(228, 63, 90));
        Portafolios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jScrollPane1.setViewportView(portafoliosList);

        addPortafolio.setText("Agregar Portafolio");
        addPortafolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPortafolioActionPerformed(evt);
            }
        });

        jButton4.setText("Borrar");

        jButton11.setText("Agregar Fichero");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PortafoliosLayout = new javax.swing.GroupLayout(Portafolios);
        Portafolios.setLayout(PortafoliosLayout);
        PortafoliosLayout.setHorizontalGroup(
            PortafoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PortafoliosLayout.createSequentialGroup()
                .addComponent(addPortafolio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
            .addGroup(PortafoliosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        PortafoliosLayout.setVerticalGroup(
            PortafoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PortafoliosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(PortafoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPortafolio)
                    .addComponent(jButton4)
                    .addComponent(jButton11)))
        );

        panelCardLayout.add(Portafolios, "card3");

        jToggleButton1.setText("Reproducir Fichero");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton7.setText("Reproducir Repositorio");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Reproducir Portafolios");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(repoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(portafoliosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImageReproductor, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToggleButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7)
                            .addGap(53, 53, 53)
                            .addComponent(jButton8))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelImageReproductor, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portafoliosBtn)
                    .addComponent(repoBtn)
                    .addComponent(jButton7)
                    .addComponent(jToggleButton1)
                    .addComponent(jButton8))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(253, 203, 158));

        menu1.setText("Inicio");

        jMenuItem1.setText("Guardar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu1.add(jMenuItem1);

        jMenuItem2.setText("Cargar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        menu1.add(jMenuItem3);

        jMenuBar1.add(menu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ciclicoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciclicoBtnActionPerformed
        control.cambioCiclico();        // TODO add your handling code here:
    }//GEN-LAST:event_ciclicoBtnActionPerformed

    private void stopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnActionPerformed
        try {
            control.stopReproduccio();        // TODO add your handling code here:
        } catch (ReproException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_stopBtnActionPerformed

    private void portafoliosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portafoliosBtnActionPerformed
        // TODO add your handling code here:
        card.show(panelCardLayout, "card3");

        portafoliosList.clearSelection();
        DefaultListModel listModel = new DefaultListModel();
        for (String item : control.showPortafolis()) {
            listModel.addElement(item);
        }
        portafoliosList.setModel(listModel);
        
                repoList2.clearSelection();
        DefaultListModel listModel2 = new DefaultListModel();
        for (String item : control.showRepositori()) {
            listModel2.addElement(item);
        }
        repoList2.setModel(listModel2);


    }//GEN-LAST:event_portafoliosBtnActionPerformed

    private void fileTxtFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileTxtFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileTxtFileActionPerformed

    private void examAddFileBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examAddFileBtn1ActionPerformed
        // TODO add your handling code here:
        File fichero;
        JFileChooser seleccion1 = new JFileChooser();
        int resultado = seleccion1.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            fichero = seleccion1.getSelectedFile();
            fileTxtFile.setText(fichero.toString());
        }
    }//GEN-LAST:event_examAddFileBtn1ActionPerformed

    private void caratulaTxtFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caratulaTxtFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caratulaTxtFileActionPerformed

    private void tipoFileComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoFileComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoFileComboBoxActionPerformed

    private void offAddFileDialogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offAddFileDialogBtnActionPerformed
        // TODO add your handling code here:
        addFileDialog.dispose();
    }//GEN-LAST:event_offAddFileDialogBtnActionPerformed

    private void onAddFileDialogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddFileDialogBtnActionPerformed
        //Conseguir la info de los otros componentes 
        String ruta = fileTxtFile.getText();
        String caratula = caratulaTxtFile.getText();
        String autor = autorTxtFile.getText();
        String codec;

        if (caratula.equals("")) {
            caratula = "C:\\Users\\MiguelDesktop\\Documents\\reproductorNetbeans\\iconMusic.jpg";
        }
        //Mandamos que se ejecute el controlador
        if (tipoFileComboBox.getItemAt(tipoFileComboBox.getSelectedIndex()).equals("Musica")) {
            codec = "mp3";
            try {
                control.addAudio(ruta, caratula, autor, codec, 1);
            } catch (ReproException e) {
                System.out.println(e.getMessage());
            }
        } else {
            codec = "jpg";
            try {
                control.addImatge(ruta, autor, codec, 1, 1);
            } catch (ReproException e) {
                System.out.println(e.getMessage());
            }
        }

        addFileDialog.dispose();


    }//GEN-LAST:event_onAddFileDialogBtnActionPerformed

    private void examAddFileBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examAddFileBtn2ActionPerformed
        File fichero;
        JFileChooser seleccion1 = new JFileChooser();
        int resultado = seleccion1.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            fichero = seleccion1.getSelectedFile();
            autorTxtFile.setText(fichero.toString());
        }
    }//GEN-LAST:event_examAddFileBtn2ActionPerformed

    private void repoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repoBtnActionPerformed
        //Cuando se elige este llama a Control para mostar los archivos de repositorio
        card.show(panelCardLayout, "card2");

        repoList.clearSelection();
        DefaultListModel listModel = new DefaultListModel();
        for (String item : control.showRepositori()) {
            listModel.addElement(item);
        }
        repoList.setModel(listModel);
    }//GEN-LAST:event_repoBtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        saveDatesDialog.setVisible(true);
        saveDatesDialog.setTitle("Guardar datos");
        saveDatesDialog.setSize(700, 300);
        saveDatesDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        File fichero;
        JFileChooser seleccion1 = new JFileChooser();
        int resultado = seleccion1.showOpenDialog(this);
        seleccion1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            fichero = seleccion1.getSelectedFile();
            fileSaveDatesTxtField.setText(fichero.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void onSaveDatesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSaveDatesBtnActionPerformed
        // TODO add your handling code here:
        String name = nameSaveDatesTxtField.getText();
        String ruta = fileSaveDatesTxtField.getText();
        ruta += "\\" + name;
        try {
            control.saveDades(ruta);
        } catch (ReproException e) {
            System.out.println(e.getMessage());
        }
        nameSaveDatesTxtField.setText("");
        fileSaveDatesTxtField.setText("");

        saveDatesDialog.dispose();

    }//GEN-LAST:event_onSaveDatesBtnActionPerformed

    private void offSaveDatesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offSaveDatesBtnActionPerformed
        // TODO add your handling code here:
        nameSaveDatesTxtField.setText("");
        fileSaveDatesTxtField.setText("");

        saveDatesDialog.dispose();
    }//GEN-LAST:event_offSaveDatesBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        File fichero;
        JFileChooser seleccion1 = new JFileChooser();
        int resultado = seleccion1.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            fichero = seleccion1.getSelectedFile();
            fileLoadDatesTxtField.setText(fichero.toString());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void onLoadDatesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLoadDatesBtnActionPerformed
        // TODO add your handling code here:
        String ruta = fileLoadDatesTxtField.getText();
        try {
            control.loadDades(ruta);
        } catch (ReproException e) {
            e.getMessage();
        }
        fileLoadDatesTxtField.setText("");
        loadDatesDialog.dispose();

    }//GEN-LAST:event_onLoadDatesBtnActionPerformed

    private void offLoadDatesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offLoadDatesBtnActionPerformed
        // TODO add your handling code here:
        fileLoadDatesTxtField.setText("");
        loadDatesDialog.dispose();
    }//GEN-LAST:event_offLoadDatesBtnActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        loadDatesDialog.setVisible(true);
        loadDatesDialog.setTitle("Guardar datos");
        loadDatesDialog.setSize(700, 300);
        loadDatesDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            control.playLlista(portafoliosList.getSelectedValuesList().get(0));        // TODO add your handling code here:
        } catch (ReproException ex) {
            //Logger.getLogger(AplicacionUB4.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            control.pauseReproduccio();        // TODO add your handling code here:
        } catch (ReproException ex) {
            // Logger.getLogger(AplicacionUB4.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        try {
            control.jumpReproduccio();        // TODO add your handling code here:
        } catch (ReproException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void randomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomBtnActionPerformed
        control.cambioReverso();        // TODO add your handling code here:
    }//GEN-LAST:event_randomBtnActionPerformed

    private void playPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playPBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playPBtnActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        try {
            control.playFitxer(repoList.getSelectedIndex());        // TODO add your handling code here:
        } catch (ReproException ex) {
            //Logger.getLogger(AplicacionUB4.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            control.playLlista();        // TODO add your handling code here:
        } catch (ReproException ex) {
            //Logger.getLogger(AplicacionUB4.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        addFileDialog.setVisible(true);
        addFileDialog.setTitle("Guardar datos");
        addFileDialog.setSize(700, 300);
        addFileDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void addPortafolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPortafolioActionPerformed
        // TODO add your handling code here:
        addPortafolioDialog.setVisible(true);
        addPortafolioDialog.setTitle("Agregar Portafolio");
        addPortafolioDialog.setSize(700, 300);
        addPortafolioDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_addPortafolioActionPerformed

    private void sizeAddPortTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeAddPortTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeAddPortTxtFieldActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        nameAddPortTxtField.setText("");
        sizeAddPortTxtField.setText("");
        addPortafolioDialog.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String nombre = nameAddPortTxtField.getText();
        String size = sizeAddPortTxtField.getText();
        int tamaño;
        if (size.equals("")) {
            tamaño = 100;
        } else {
            tamaño = Integer.parseInt(size);
        }

        try {
            control.addPortafoli(nombre, tamaño);
        } catch (ReproException ex) {
            //Logger.getLogger(AplicacionUB4.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }

        nameAddPortTxtField.setText("");
        sizeAddPortTxtField.setText("");
        addPortafolioDialog.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // TODO add your handling code here:
            control.removeFitxer(repoList.getSelectedIndex());
        } catch (ReproException ex) {
            //Logger.getLogger(AplicacionUB4.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        addFilePortafolioDialog.setVisible(true);
        addFilePortafolioDialog.setTitle("Guardar datos");
        addFilePortafolioDialog.setSize(700, 300);
        addFilePortafolioDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        addFilePortafolioDialog.dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            // TODO add your handling code here:
            control.addFitxer(portafoliosList.getSelectedValuesList().get(0), repoList2.getSelectedIndex());
        } catch (ReproException ex) {
            //Logger.getLogger(AplicacionUB4.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
        addFilePortafolioDialog.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacionUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacionUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacionUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacionUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicacionUB4().setVisible(true);

            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Portafolios;
    private javax.swing.JPanel Repository;
    private javax.swing.JDialog addFileDialog;
    private javax.swing.JDialog addFilePortafolioDialog;
    private javax.swing.JButton addPortafolio;
    private javax.swing.JDialog addPortafolioDialog;
    private javax.swing.JTextField autorTxtFile;
    private javax.swing.JTextField caratulaTxtFile;
    private javax.swing.JToggleButton ciclicoBtn;
    private javax.swing.JButton examAddFileBtn1;
    private javax.swing.JButton examAddFileBtn2;
    private javax.swing.JTextField fileLoadDatesTxtField;
    private javax.swing.JTextField fileSaveDatesTxtField;
    private javax.swing.JTextField fileTxtFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelImageReproductor;
    private javax.swing.JDialog loadDatesDialog;
    private javax.swing.JMenu menu1;
    private javax.swing.JTextField nameAddPortTxtField;
    private javax.swing.JTextField nameSaveDatesTxtField;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton offAddFileDialogBtn;
    private javax.swing.JButton offLoadDatesBtn;
    private javax.swing.JButton offSaveDatesBtn;
    private javax.swing.JButton onAddFileDialogBtn;
    private javax.swing.JButton onLoadDatesBtn;
    private javax.swing.JButton onSaveDatesBtn;
    private javax.swing.JPanel panelCardLayout;
    private javax.swing.JButton playPBtn;
    private javax.swing.JButton portafoliosBtn;
    private javax.swing.JList<String> portafoliosList;
    private javax.swing.JToggleButton randomBtn;
    private javax.swing.JButton repoBtn;
    private javax.swing.JList<String> repoList;
    private javax.swing.JList<String> repoList2;
    private javax.swing.JDialog saveDatesDialog;
    private javax.swing.JTextField sizeAddPortTxtField;
    private javax.swing.JButton stopBtn;
    private javax.swing.JComboBox<String> tipoFileComboBox;
    // End of variables declaration//GEN-END:variables
}
